### ISSUE TITLE
编译项目中遇到的坑

### ISSUE THREAD

**Issue by w119214972** [imistyrain/CarPlateAndroid#1]
感谢作者给出这么实用的demo！
主要想说的是编译当中遇到的问题：
1.目前的AS默认的gradle版本为2.10，而此项目gradle版本为2.5，因此配置项差别比较大，我改了很久，最后还是编译不过，所以最好还是使用gradle2.5去编译。
2.java版本为1.7,如果是1.8，运行会报错。
3.app的builde.gradle配置
`android.ndk`
 `{`
`moduleName = "mrcarproc"`
 `stl = "gnustl_shared"`
  `cppFlags += "-IG:/ProjectCode/EasyPR_Android-master/EasyPR_Android-master/PlateRecognizer/OpencvNative/jni/include/opencv".toString()`
  `cppFlags += "-IG:/ProjectCode/EasyPR_Android-master/EasyPR_Android-master/PlateRecognizer/OpencvNative/jni/include".toString()`
`cppFlags += "-IG:/ProjectCode/CarPlateAndroid-master/CarPlateAndroid-master/app/src/main/jni/include".toString()`
`cppFlags += "-IG:/ProjectCode/CarPlateAndroid-master/CarPlateAndroid-master/app/src/main/jni".toString()`
  `cppFlags +="-fexceptions"`
  `cppFlags +="-std=c++11"`
   `cppFlags+="-llog"`
   `ldLibs += ["android", "EGL", "GLESv2", "dl", "log", "z","gomp"]`
  `}`

这几个是本地头文件的路径，需按实际情况做更改。其中opencv的头文件，作者没有给出，本人从EasyPR中copy过来的。

> G:/ProjectCode/EasyPR_Android-master/EasyPR_Android-master/PlateRecognizer/OpencvNative/jni/include/opencv
> 
> G:/ProjectCode/EasyPR_Android-master/EasyPR_Android-master/PlateRecognizer/OpencvNative/jni/include
> 
> G:/ProjectCode/CarPlateAndroid-master/CarPlateAndroid-master/app/src/main/jni/include
> 
> G:/ProjectCode/CarPlateAndroid-master/CarPlateAndroid-master/app/src/main/jni

最后，想请问下作者，为什么车牌的英文+数字识别率挺高的，而汉字识别率不高？

**Comment by imistyrain** [comment]
非常感谢您提出的建议，这些问题确实也是我构建这些项目时遇到并一一解决的。
这个版本的构建有点老，我已经更换了新版本，大大简化了构建步骤，但是由于删除了git文件，没法上传。
数字和字母相对来说比较容易，因此识别率还是可以的。汉字由于训练样本过少，因此识别率还不是很理想，这点easypr中也曾提及，当然如果有更多的样本的话，识别率还是可以的。
最重要的一点，车牌的重点是定位检测，分割和字符识别相对而言都有成熟的解决方法。
当然特定场景下的检测也是容易搞定的，难的的是用一套方案来搞定所有场景。

**Comment by MIkeeJY** [comment]
Error:Execution failed for task ':app:compileArmeabi-v7aDebugMrcarprocSharedLibraryMrcarprocMainCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling main.cpp.
      C++ compiler failed while compiling params.cpp.
      C++ compiler failed while compiling feature.cpp.
      C++ compiler failed while compiling core_func.cpp.
      C++ compiler failed while compiling chars_segment.cpp.
      C++ compiler failed while compiling chars_recognise.cpp.
      C++ compiler failed while compiling chars_identify.cpp.
      C++ compiler failed while compiling marcar.cpp.
      C++ compiler failed while compiling plate_judge.cpp.
      C++ compiler failed while compiling plate_locate.cpp.
      ...and 15 more failures.
  See the complete log at: file:///Users/hackest/Downloads/CarPlateAndroid-master/app/build/tmp/compileArmeabi-v7aDebugMrcarprocSharedLibraryMrcarprocMainCpp/output.txt

**Comment by imistyrain** [comment]
已经把整个project更新，应该不会存在之前的问题了
